export const SIDEBAR_TOGGLED = 'SIDEBAR_TOGGLED';
export const MESSAGE_SENT = 'MESSAGE_SENT';
export const RESPONSE_RECEIVED = 'RESPONSE_RECEIVED';
export const LINK = 'LINK';
export const RESET_LINK = 'RESET_LINK';
export const SCROLL = 'SCROLL'

export const TASK_CREATED = 'TASK_CREATED';
export const TASKS_LOADED = 'TASKS_LOADED';
export const CURRENT_TASK_CHANGED = 'CURRENT_TASK_CHANGED';
export const TASK_DELETED = 'TASK_DELETED';
export const TASK_SAVED = 'TASK_SAVED';
export const MODAL_TOGGLED = 'MODAL_TOGGLED';
export const SHOW_MODAL = 'SHOW_MODAL';

export const MEMBER_CREATED = 'MEMBER_CREATED';
export const MEMBERS_LOADED = 'MEMBERS_LOADED';
export const CURRENT_MEMBER_CHANGED = 'CURRENT_MEMBER_CHANGED';
export const MEMBER_DELETED = 'MEMBER_DELETED';
export const MEMBER_SAVED = 'MEMBER_SAVED';
export const ROLE_FILTER_CHANGED = 'ROLE_FILTER_CHANGED';



// ---------------
// export const SPRINT_REF_SET = 'SPRINT_REF_SET';
// export const SPRINT_PLANNING_REF_SET = 'SPRINT_PLANNING_REF_SET';
// export const SPRINT_REVIEW_REF_SET = 'SPRINT_REVIEW_REF_SET';
// export const DAILY_SCRUM_REF_SET = 'DAILY_SCRUM_REF_SET';
export const SPRINT_RETRO_REF_SET = 'SPRINT_RETRO_REF_SET';

export const RESET_PARAMS = 'RESET_PARAMS';

