export const SIDEBAR_TOGGLED = 'SIDEBAR_TOGGLED';
export const MESSAGE_SENT = 'MESSAGE_SENT';
export const RESPONSE_RECEIVED = 'RESPONSE_RECEIVED';
export const LINK = 'LINK';
export const RESET_LINK = 'RESET_LINK';
export const SCROLL = 'SCROLL';
export const RESET_SCROLL = 'RESET_SCROLL';

export const TASK_CREATED = 'TASK_CREATED';
export const TASKS_LOADED = 'TASKS_LOADED';
export const CURRENT_TASK_CHANGED = 'CURRENT_TASK_CHANGED';
export const TASK_DELETED = 'TASK_DELETED';
export const TASK_SAVED = 'TASK_SAVED';
export const MODAL_TOGGLED = 'MODAL_TOGGLED';
export const SHOW_TASK_MODAL = 'SHOW_TASK_MODAL';

export const MEMBER_CREATED = 'MEMBER_CREATED';
export const MEMBERS_LOADED = 'MEMBERS_LOADED';
export const CURRENT_MEMBER_CHANGED = 'CURRENT_MEMBER_CHANGED';
export const MEMBER_DELETED = 'MEMBER_DELETED';
export const MEMBER_SAVED = 'MEMBER_SAVED';
export const ROLE_FILTER_CHANGED = 'ROLE_FILTER_CHANGED';
export const SHOW_MEMBER_MODAL = 'SHOW_MEMBER_MODAL';


// ---------------
export const SET_SPRINT_REF = 'SET_SPRINT_REF';
export const SET_SPRINT_PLANNING_REF = 'SET_SPRINT_PLANNING_REF';
export const SET_SPRINT_REVIEW_REF = 'SET_SPRINT_REVIEW_REF';
export const SET_DAILY_SCRUM_REF = 'SETDAILY_SCRUM_REF';
export const SET_SPRINT_RETRO_REF = 'SET_SPRINT_RETRO_REF';

export const SET_PO_REF = 'SET_PO_REF';
export const SET_SM_REF = 'SET_SM_REF';
export const SET_DEV_REF = 'SET_DEV_REF';

export const RESET_PARAMS = 'RESET_PARAMS';

